"""empty message

Revision ID: 1eaf4aaa6003
Revises: 53c834f9ae03
Create Date: 2024-12-05 15:58:25.719522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eaf4aaa6003'
down_revision = '53c834f9ae03'
branch_labels = None
depends_on = None


def upgrade():
    # 1. 一旦null許可で追加
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
    
    # 2. 既存データにdefault@example.comをセット
    op.execute("UPDATE users SET email='default@example.com' WHERE email IS NULL;")
    
    # 3. now make it NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
